# Setup
title:               Exalted Reincarnated
description:         'A top-to-bottom rewrite of Exalted'
url:                 https://exaltedreincarnated.org/
baseurl:             '_pages'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dragonmystic

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
