remote_theme: poole/lanyon

# Setup
title:               Exalted Reincarnated
baseurl:             ''
paginate:            5
permalink:           pretty


# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


theme: jekyll-theme-cayman