remote_theme:       Dragonmystic707/lanyon/gh-pages

# Setup
title:               Exalted Reincarnated
description:         'A top-to-bottom rewrite of Exalted'
url:                 https://exaltedreincarnated.org
auto_ids:            true
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dragonmystic

# Gems
plugins:
  - jekyll-paginate
